Fix: .. is not a function after deploy
The daysjs import was causing an error when we deploy the
application.
ref: https://stackoverflow.com/questions/76754734/error-in-production-build-with-vite-react-error-in-uncaught-typeerror-is-n